//! `rolter init` — generate a production deployment's config and secrets (#854).
//!
//! [`crate::preflight`] tells an operator what is wrong. This tells them what to
//! write, which is the other half of the same problem: `rolter check` fails on a
//! missing `ROLTER_KEK` and says "generate one with `openssl rand -hex 32`", and
//! then the operator has to invent the rest of the file around it.
//!
//! Nothing here is interactive. A generator that prompts cannot run in the
//! Dockerfile, the Helm hook or the CI job that is exactly where a production
//! deployment is assembled, and an operator who has to answer six questions to
//! get a `.env` will hand-write one instead. Flags carry the choices; the
//! defaults are the secure ones.
//!
//! ## What it will not do
//!
//! It will not touch `easy-up`. The local path is deliberately frictionless and
//! zero-config, and #854's design constraint is that the two paths stay apart:
//! local stays loose, production stays guided. `rolter init` is opt-in and
//! writes files an operator asked for.
//!
//! It will not overwrite an existing file without `--force`. A generator that
//! silently regenerates a KEK destroys every credential encrypted under the old
//! one — the failure is total, delayed, and looks like data corruption.

use std::io::Write as _;
use std::path::{Path, PathBuf};

use anyhow::Context as _;
use clap::{Args, ValueEnum};
use rand::Rng as _;

/// Bytes drawn for each generated secret. 32 bytes is 256 bits, which is what
/// the KEK is stretched to anyway and more than any of the bearer tokens need.
const SECRET_BYTES: usize = 32;

/// Which deployment this config is for. The difference is not cosmetic: the
/// production profile binds the management plane to loopback and fails auth
/// closed, both of which would make the local path stop working.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum, Default)]
pub enum Profile {
    /// hardened defaults for a real deployment
    #[default]
    Production,
    /// the loose defaults `easy-up` runs with, for a config you intend to
    /// develop against rather than ship
    Local,
}

#[derive(Args, Debug)]
pub struct InitArgs {
    /// directory to write into
    #[arg(long, default_value = ".")]
    pub out_dir: PathBuf,

    /// gateway config filename, relative to `--out-dir`
    #[arg(long, default_value = "rolter.toml")]
    pub config: String,

    /// environment filename, relative to `--out-dir`
    #[arg(long, default_value = ".env")]
    pub env_file: String,

    /// deployment profile
    #[arg(long, value_enum, default_value_t = Profile::Production)]
    pub profile: Profile,

    /// postgres URL to write into the environment; omit to leave it blank for
    /// the platform to inject
    #[arg(long)]
    pub database_url: Option<String>,

    /// redis URL to write into the environment
    #[arg(long)]
    pub redis_url: Option<String>,

    /// clickhouse HTTP URL to write into the environment. Both the gateway and
    /// the control plane read this one variable — the gateway writes usage rows
    /// there, the dashboard reads them back — so leaving it out is what makes
    /// the analytics screens empty forever (#929)
    #[arg(long)]
    pub clickhouse_url: Option<String>,

    /// print the generated environment to stdout instead of writing it, for
    /// piping into a secret manager rather than leaving secrets on disk
    #[arg(long)]
    pub print: bool,

    /// overwrite existing files
    #[arg(long)]
    pub force: bool,

    /// write only the environment file, leaving the gateway config alone
    #[arg(long)]
    pub env_only: bool,
}

/// A freshly generated secret, hex-encoded.
fn secret() -> String {
    let mut bytes = [0u8; SECRET_BYTES];
    rand::rng().fill_bytes(&mut bytes);
    let mut s = String::with_capacity(bytes.len() * 2);
    const HEX_CHARS: &[u8; 16] = b"0123456789abcdef";
    for &b in &bytes {
        s.push(HEX_CHARS[(b >> 4) as usize] as char);
        s.push(HEX_CHARS[(b & 0x0f) as usize] as char);
    }
    s
}

/// The environment file's contents.
///
/// Takes the secrets rather than generating them so a test can assert on the
/// layout without matching random hex, and so `--print` and the file path
/// produce byte-identical output.
fn render_env(args: &InitArgs, secrets: &Secrets) -> String {
    let mut out = String::new();
    let profile = match args.profile {
        Profile::Production => "production",
        Profile::Local => "local",
    };
    out.push_str(&format!(
        "# generated by `rolter init --profile {profile}`\n\
         # secrets below are unique to this deployment. treat this file as a credential:\n\
         # keep it out of version control, and prefer piping `rolter init --print` into a\n\
         # secret manager over leaving it on disk.\n\n"
    ));

    out.push_str("# key-encryption key for provider secrets at rest (aes-256-gcm).\n");
    out.push_str(
        "# rotating this without re-encrypting strands every stored credential — it is not\n\
         # a password, it is the key the ciphertext is under.\n",
    );
    out.push_str(&format!("ROLTER_KEK={}\n\n", secrets.kek));

    out.push_str("# bearer token for the management API and /internal/snapshot.\n");
    out.push_str("# without it both are unauthenticated.\n");
    out.push_str(&format!("ROLTER_ADMIN_TOKEN={}\n\n", secrets.admin_token));

    out.push_str("# shared secret between the control plane and the gateways that poll it.\n");
    out.push_str(&format!(
        "ROLTER_INTERNAL_TOKEN={}\n\n",
        secrets.internal_token
    ));

    out.push_str(
        "# deployment-wide pepper mixed into virtual-key digests. a leaked digest is\n\
         # useless without it, so it must be identical across every replica and must not\n\
         # change once keys have been issued.\n",
    );
    out.push_str(&format!("ROLTER_KEY_PEPPER={}\n\n", secrets.key_pepper));

    out.push_str(
        "# deployment-wide pepper mixed into the stored digests of sign-in sessions,\n\
         # invitation links, scim tokens and mfa recovery codes, and into the failed-login\n\
         # throttle's redis keys. it must be identical on every control-plane replica.\n\
         # changing it ends every live session and voids open invitations, scim tokens\n\
         # and recovery codes.\n",
    );
    out.push_str(&format!(
        "ROLTER_SESSION_PEPPER={}\n\n",
        secrets.session_pepper
    ));

    out.push_str("# datastores\n");
    out.push_str(&format!(
        "ROLTER_DATABASE_URL={}\n",
        args.database_url.as_deref().unwrap_or("")
    ));
    out.push_str(&format!(
        "ROLTER_REDIS_URL={}\n",
        args.redis_url.as_deref().unwrap_or("")
    ));
    out.push_str(
        "# read by both processes: the gateway writes request, usage and cost rows here\n\
         # and the dashboard reads them back. leave it empty and the Usage, Costs and Logs\n\
         # screens stay empty however much traffic is served.\n",
    );
    out.push_str(&format!(
        "CLICKHOUSE_URL={}\n\n",
        args.clickhouse_url.as_deref().unwrap_or("")
    ));

    out.push_str("# listeners\n");
    out.push_str("ROLTER_HOST=0.0.0.0\nROLTER_PORT=4000\n");
    match args.profile {
        Profile::Production => {
            out.push_str(
                "# the management plane is bound to loopback: it is an admin surface, not a\n\
                 # public one. put it behind an ingress that terminates TLS if you need it\n\
                 # reachable, rather than opening the bind.\n",
            );
            out.push_str("ROLTER_CONTROL_HOST=127.0.0.1\n");
        }
        Profile::Local => out.push_str("ROLTER_CONTROL_HOST=0.0.0.0\n"),
    }
    out.push_str("ROLTER_CONTROL_PORT=4001\n\nROLTER_CONFIG=");
    out.push_str(&args.config);
    out.push('\n');
    out.push_str("RUST_LOG=info\n");
    out
}

/// The generated secrets, kept together so the renderer cannot silently reuse
/// one value in two places.
struct Secrets {
    kek: String,
    admin_token: String,
    internal_token: String,
    key_pepper: String,
    session_pepper: String,
}

impl Secrets {
    fn generate() -> Self {
        Self {
            kek: secret(),
            admin_token: secret(),
            internal_token: secret(),
            key_pepper: secret(),
            session_pepper: secret(),
        }
    }
}

/// The gateway config for this profile: the bundled example, with the
/// production profile's hardening folded into its existing `[server]` table.
///
/// Folded in, not appended: the example already declares `[server]`, and a
/// second one is a duplicate-key TOML error rather than a merge.
fn render_config(profile: Profile) -> String {
    let base = crate::easy_up::EXAMPLE_CONFIG;
    match profile {
        Profile::Local => base.to_string(),
        Profile::Production => {
            const HARDENING: &str = "\
# set by `rolter init --profile production`. without it, revoking the last
# virtual key silently *opens* the data plane rather than closing it — the
# default defers to the deployment shape, and a production deployment should
# state the answer rather than let it be inferred.
require_auth = true
";
            match base.split_once("[server]\n") {
                Some((head, tail)) => format!("{head}[server]\n{HARDENING}{tail}"),
                // the example lost its [server] table: emit our own rather than
                // silently dropping the hardening
                None => format!("{base}\n[server]\n{HARDENING}"),
            }
        }
    }
}

/// Write `contents` to `path`, refusing to clobber unless `force`.
///
/// On unix the file is created 0600. A `.env` holding the KEK is a credential;
/// creating it world-readable and fixing it afterwards leaves a window, so the
/// mode goes on at creation.
fn write_file(path: &Path, contents: &str, force: bool) -> anyhow::Result<()> {
    if path.exists() && !force {
        anyhow::bail!(
            "{} already exists. Pass --force to overwrite it — but read the warning first: \
             regenerating ROLTER_KEK strands every credential encrypted under the old one.",
            path.display()
        );
    }
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
    }

    let mut options = std::fs::OpenOptions::new();
    options.write(true).create(true).truncate(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt as _;
        options.mode(0o600);
    }
    let mut file = options
        .open(path)
        .with_context(|| format!("writing {}", path.display()))?;
    file.write_all(contents.as_bytes())
        .with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

pub async fn run(args: InitArgs) -> anyhow::Result<()> {
    let secrets = Secrets::generate();
    let env = render_env(&args, &secrets);

    if args.print {
        // no file touched at all, so this stays safe to run in a pipeline that
        // has nowhere durable to write
        print!("{env}");
        return Ok(());
    }

    let env_path = args.out_dir.join(&args.env_file);
    write_file(&env_path, &env, args.force)?;
    let mut written = vec![env_path.clone()];

    if !args.env_only {
        let config_path = args.out_dir.join(&args.config);
        write_file(&config_path, &render_config(args.profile), args.force)?;
        written.push(config_path);
    }

    for path in &written {
        println!("wrote {}", path.display());
    }
    println!();
    match args.profile {
        Profile::Production => {
            println!(
                "next: load the environment and run `rolter check --strict` before starting \
                 anything. It validates exactly what this generated, so a passing check means \
                 the deployment will not start degraded."
            );
            if args.database_url.is_none() {
                println!(
                    "\nROLTER_DATABASE_URL is blank. Fill it in, or inject it from your \
                     platform's secret store — `rolter check` treats it as fatal, because \
                     without it the control plane keeps every provider, route, key and budget \
                     in memory and loses them on restart."
                );
            }
        }
        Profile::Local => {
            println!("next: `rolter easy-up`. This profile is the loose one — do not ship it.")
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args(profile: Profile) -> InitArgs {
        InitArgs {
            out_dir: PathBuf::from("."),
            config: "rolter.toml".to_string(),
            env_file: ".env".to_string(),
            profile,
            database_url: None,
            redis_url: None,
            clickhouse_url: None,
            print: false,
            force: false,
            env_only: false,
        }
    }

    fn fixed_secrets() -> Secrets {
        Secrets {
            kek: "kek".to_string(),
            admin_token: "admin".to_string(),
            internal_token: "internal".to_string(),
            key_pepper: "pepper".to_string(),
            session_pepper: "session-pepper".to_string(),
        }
    }

    #[test]
    fn generated_secrets_are_distinct_and_full_length() {
        let s = Secrets::generate();
        let all = [
            &s.kek,
            &s.admin_token,
            &s.internal_token,
            &s.key_pepper,
            &s.session_pepper,
        ];
        for value in all {
            assert_eq!(
                value.len(),
                SECRET_BYTES * 2,
                "expected {SECRET_BYTES} bytes of hex"
            );
            assert!(value.chars().all(|c| c.is_ascii_hexdigit()));
        }
        // reusing one secret in two roles would mean a leaked admin token also
        // decrypts every stored credential
        for (i, a) in all.iter().enumerate() {
            for b in all.iter().skip(i + 1) {
                assert_ne!(a, b, "two roles share a secret");
            }
        }
    }

    #[test]
    fn two_runs_never_produce_the_same_secret() {
        assert_ne!(Secrets::generate().kek, Secrets::generate().kek);
    }

    #[test]
    fn the_production_profile_binds_the_control_plane_to_loopback() {
        let env = render_env(&args(Profile::Production), &fixed_secrets());
        assert!(env.contains("ROLTER_CONTROL_HOST=127.0.0.1"), "{env}");
        // the data plane is the public surface and stays open
        assert!(env.contains("ROLTER_HOST=0.0.0.0"), "{env}");
    }

    #[test]
    fn the_local_profile_keeps_the_loose_bind() {
        let env = render_env(&args(Profile::Local), &fixed_secrets());
        assert!(env.contains("ROLTER_CONTROL_HOST=0.0.0.0"), "{env}");
    }

    #[test]
    fn the_environment_sets_every_variable_the_preflight_gate_requires() {
        let mut a = args(Profile::Production);
        a.database_url = Some("postgres://user:pw@db:5432/rolter".to_string());
        a.redis_url = Some("redis://cache:6379".to_string());
        let env = render_env(&a, &fixed_secrets());
        for var in [
            "ROLTER_KEK",
            "ROLTER_ADMIN_TOKEN",
            "ROLTER_INTERNAL_TOKEN",
            "ROLTER_KEY_PEPPER",
            "ROLTER_SESSION_PEPPER",
            "ROLTER_DATABASE_URL",
            "ROLTER_REDIS_URL",
        ] {
            let line = format!("{var}=");
            let value = env
                .lines()
                .find(|l| l.starts_with(&line))
                .unwrap_or_else(|| panic!("{var} missing from:\n{env}"));
            assert_ne!(value, line, "{var} was written empty");
        }
    }

    #[test]
    fn each_secret_is_written_under_its_own_name() {
        // `Secrets` keeps the values apart; this pins that the renderer does not
        // put one of them under a second name, the two peppers above all
        let env = render_env(&args(Profile::Production), &fixed_secrets());
        for (var, value) in [
            ("ROLTER_KEK", "kek"),
            ("ROLTER_ADMIN_TOKEN", "admin"),
            ("ROLTER_INTERNAL_TOKEN", "internal"),
            ("ROLTER_KEY_PEPPER", "pepper"),
            ("ROLTER_SESSION_PEPPER", "session-pepper"),
        ] {
            let line = format!("{var}={value}");
            assert!(
                env.lines().any(|l| l == line),
                "{line} missing from:\n{env}"
            );
        }
    }

    #[test]
    fn a_blank_database_url_is_written_rather_than_omitted() {
        // an operator injecting it from a platform secret store still wants the
        // key present, so the file documents what has to be filled
        let env = render_env(&args(Profile::Production), &fixed_secrets());
        assert!(env.contains("\nROLTER_DATABASE_URL=\n"), "{env}");
    }

    #[test]
    fn the_production_config_closes_auth_and_the_local_one_does_not() {
        let production = render_config(Profile::Production);
        assert!(production.contains("require_auth = true"), "{production}");
        assert!(!render_config(Profile::Local).contains("require_auth = true"));
    }

    #[test]
    fn the_generated_config_parses() {
        for profile in [Profile::Production, Profile::Local] {
            let text = render_config(profile);
            let parsed: Result<rolter_core::GatewayConfig, _> = toml::from_str(&text);
            assert!(
                parsed.is_ok(),
                "{profile:?} config does not parse: {:?}",
                parsed.err()
            );
        }
    }

    #[test]
    fn writing_refuses_to_clobber_without_force() {
        let dir = std::env::temp_dir().join(format!("rolter-init-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let path = dir.join(".env");

        write_file(&path, "first", false).unwrap();
        let err = write_file(&path, "second", false).unwrap_err().to_string();
        assert!(err.contains("--force"), "{err}");
        assert!(
            err.contains("strands every credential"),
            "the refusal must say why regeneration is dangerous: {err}"
        );
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "first");

        write_file(&path, "second", true).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "second");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[cfg(unix)]
    #[test]
    fn a_generated_env_file_is_not_world_readable() {
        use std::os::unix::fs::PermissionsExt as _;

        let dir = std::env::temp_dir().join(format!("rolter-init-mode-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let path = dir.join(".env");
        write_file(&path, "ROLTER_KEK=secret", false).unwrap();

        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(mode & 0o077, 0, "group/other can read {path:?}: {mode:o}");

        let _ = std::fs::remove_dir_all(&dir);
    }
    /// The point of the pair: what `init` writes is exactly what `check` gates
    /// on. If these two drift, an operator follows the documented path and is
    /// still told their deployment is broken.
    #[test]
    fn the_generated_environment_passes_the_preflight_gate() {
        use std::collections::HashMap;

        struct GeneratedEnv(HashMap<String, String>);
        impl crate::preflight::Env for GeneratedEnv {
            fn get(&self, key: &str) -> Option<String> {
                self.0.get(key).cloned().filter(|v| !v.trim().is_empty())
            }
        }

        let mut a = args(Profile::Production);
        a.database_url = Some("postgres://user:pw@db:5432/rolter".to_string());
        a.redis_url = Some("redis://cache:6379".to_string());
        a.clickhouse_url = Some("http://clickhouse:8123".to_string());
        let rendered = render_env(&a, &Secrets::generate());

        // parse it back the way a shell or container runtime would
        let parsed: HashMap<String, String> = rendered
            .lines()
            .filter(|l| !l.trim_start().starts_with('#') && l.contains('='))
            .filter_map(|l| l.split_once('='))
            .map(|(k, v)| (k.trim().to_string(), v.trim().to_string()))
            .collect();

        let findings = crate::preflight::run_checks(&GeneratedEnv(parsed));
        let titles: Vec<&str> = findings.iter().map(|f| f.title.as_str()).collect();
        assert!(
            findings.is_empty(),
            "a freshly generated production environment must pass cleanly, got: {titles:?}"
        );
    }

    #[test]
    fn the_local_profile_is_deliberately_not_production_clean() {
        use std::collections::HashMap;

        struct GeneratedEnv(HashMap<String, String>);
        impl crate::preflight::Env for GeneratedEnv {
            fn get(&self, key: &str) -> Option<String> {
                self.0.get(key).cloned().filter(|v| !v.trim().is_empty())
            }
        }

        let rendered = render_env(&args(Profile::Local), &Secrets::generate());
        let parsed: HashMap<String, String> = rendered
            .lines()
            .filter(|l| !l.trim_start().starts_with('#') && l.contains('='))
            .filter_map(|l| l.split_once('='))
            .map(|(k, v)| (k.trim().to_string(), v.trim().to_string()))
            .collect();

        // the two paths are meant to differ; this pins that the difference is
        // real rather than accidental, and that `check` is what reports it
        let findings = crate::preflight::run_checks(&GeneratedEnv(parsed));
        assert!(
            findings.iter().any(|f| f.title.contains("0.0.0.0")),
            "the local profile should trip the exposure check"
        );
    }
}
