#!/usr/bin/env bash
# runs the `no agent session urls (pr body)` step of .github/workflows/ci.yml
# against a fake `gh` and a fake clock, and checks its verdict.
#
# on a pull_request run the step reads the body live from the api, not from
# the event payload, which was frozen when the event fired (#2035). a step that
# went back to the payload would pass every pr whose url arrived while the gate
# was running, and nothing else would notice, so the first case hands the step
# a clean payload body and a dirty live one and requires red. the dispatch and
# merge-queue lookups (#1523, #1318) go through the same fake.
#
# the step is extracted from the workflow rather than copied here, so the test
# follows the step when it changes. bash 3.2 compatible, so it runs under
# macos's /bin/bash as well as in ci.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
workflow="$root/.github/workflows/ci.yml"
step_name="no agent session urls (pr body)"

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# the whole step, from its `- name:` line to the first non-blank line indented
# less than its keys: the next step, a comment above it, or the next job
awk -v step="      - name: $step_name" '
  $0 == step { in_step = 1; print; next }
  in_step && NF && !/^        / { exit }
  in_step { print }
' "$workflow" >"$work/step.yml"

# its run: block, de-indented
awk '
  /^        run: \|$/ { grab = 1; next }
  grab && /^$/ { print ""; next }
  grab && /^          / { print substr($0, 11); next }
  grab { exit }
' "$work/step.yml" >"$work/step.sh"

for marker in 'check-agent-session-urls.sh' 'EVENT_NAME'; do
  if ! grep -qF "$marker" "$work/step.sh"; then
    echo "error: could not extract the run: block of '$step_name' from $workflow ($marker missing)" >&2
    exit 1
  fi
done

failures=0

# the wiring the run: block cannot show: where the number comes from, and that
# nothing hands the step the frozen body
static_check() {
  # static_check DESCRIPTION PRESENT|ABSENT TEXT
  local found=no
  if grep -qF -- "$3" "$work/step.yml"; then found=yes; fi
  if { [ "$2" = PRESENT ] && [ "$found" = no ]; } || { [ "$2" = ABSENT ] && [ "$found" = yes ]; }; then
    echo "FAIL [workflow wiring] $1" >&2
    failures=$((failures + 1))
  fi
}
# shellcheck disable=SC2016 # the workflow text itself, not a shell expansion
static_check "the step takes the pr number from the payload" PRESENT \
  'PR_NUMBER: ${{ github.event.pull_request.number }}'
static_check "the step never reads the body the payload froze" ABSENT \
  'github.event.pull_request.body'

# ── fakes ─────────────────────────────────────────────────────────────────────
bin="$work/bin"
mkdir -p "$bin"

# records each wait instead of waiting
cat >"$bin/sleep" <<'EOF'
#!/usr/bin/env bash
echo "$1" >>"$FAKE/slept"
EOF

# gh: serves the single-pr endpoint and the open-pr listing out of
# $FAKE/pulls.json. $FAKE/faults holds how many of the next calls fail with a
# 502, and a non-empty $FAKE/respond replaces the answer to every call that
# gets through
cat >"$bin/gh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
[ "$1" = api ] && [ "$#" -eq 2 ] || { echo "fake gh: unexpected call: $*" >&2; exit 2; }
path=$2
echo "$path" >>"$FAKE/calls"
faults=$(cat "$FAKE/faults")
if [ "$faults" -gt 0 ]; then
  echo $((faults - 1)) >"$FAKE/faults"
  echo "HTTP 502: Bad Gateway (https://api.github.com/$path)" >&2
  exit 1
fi
if [ -s "$FAKE/respond" ]; then
  cat "$FAKE/respond"
  exit 0
fi
case $path in
  "repos/rolter-ai/rolter/pulls?state=open&per_page=100")
    cat "$FAKE/pulls.json" ;;
  repos/rolter-ai/rolter/pulls/*)
    number=${path##*/}
    case $number in
      '' | *[!0-9]*) echo "fake gh: bad pr number in $path" >&2; exit 2 ;;
    esac
    if ! jq -e --argjson n "$number" 'any(.[]; .number == $n)' "$FAKE/pulls.json" >/dev/null; then
      echo '{"message":"Not Found","status":"404"}'
      echo "gh: Not Found (HTTP 404)" >&2
      exit 1
    fi
    jq --argjson n "$number" '.[] | select(.number == $n)' "$FAKE/pulls.json" ;;
  *) echo "fake gh: unexpected path: $path" >&2; exit 2 ;;
esac
EOF
chmod +x "$bin/sleep" "$bin/gh"

# ── harness ───────────────────────────────────────────────────────────────────
clean="Closes #2035"
# the footer a pr-authoring tool appends, and another agent's trailer
dirty=$'Closes #2035\n\n_Generated by [Claude Code](https://claude.ai/code/session_0123456789)_'
trailer=$'Closes #2035\n\nSomeAgent-Session: https://agent.example.com/s/0123456789'
queue_ref="gh-readonly-queue/master/pr-2035-0123456789abcdef0123456789abcdef01234567"

case_name=""
case_dir=""

# start_case NAME: one open pr, #2035 from fix/2035-live-body, with a clean
# body both live and in the payload. callers adjust before run_step
start_case() {
  case_name=$1
  case_dir="$work/$(echo "$1" | tr -c 'a-zA-Z0-9\n' '-')"
  mkdir -p "$case_dir"
  echo 0 >"$case_dir/faults"
  : >"$case_dir/respond"
  : >"$case_dir/calls"
  : >"$case_dir/slept"
  payload_body=$clean
  set_live_body "$clean"
}

# set_live_body BODY: the body the api answers with now; "null" for none
set_live_body() {
  local body_json
  if [ "$1" = null ]; then body_json=null; else body_json=$(jq -n --arg b "$1" '$b'); fi
  jq -n --argjson body "$body_json" '[
    {number: 2035, body: $body,
     head: {ref: "fix/2035-live-body", sha: "0123456789abcdef0123456789abcdef01234567"},
     base: {sha: "89abcdef0123456789abcdef0123456789abcdef"}}
  ]' >"$case_dir/pulls.json"
}

# run_step EVENT [PR_NUMBER] [REF_NAME]: runs the extracted step from the repo
# root, as the workflow does. PR_BODY carries the payload's frozen body, which
# is what a step that regressed to the payload would read
run_step() {
  local event=$1 number=${2-2035} ref=${3-} rc=0
  (
    cd "$root"
    env -i \
      PATH="$bin:$PATH" HOME="$HOME" TMPDIR="${TMPDIR:-/tmp}" FAKE="$case_dir" \
      EVENT_NAME="$event" PR_NUMBER="$number" PR_BODY="$payload_body" \
      GH_TOKEN=fake-token REPO=rolter-ai/rolter REF_NAME="$ref" \
      bash --noprofile --norc -eo pipefail "$work/step.sh"
  ) >"$case_dir/out" 2>&1 || rc=$?
  echo "$rc" >"$case_dir/rc"
}

check() {
  # check DESCRIPTION ACTUAL EXPECTED
  if [ "$2" != "$3" ]; then
    echo "FAIL [$case_name] $1: expected '$3', got '$2'" >&2
    failures=$((failures + 1))
  fi
}

expect_rc() { check "exit code" "$(cat "$case_dir/rc")" "$1"; }
expect_slept() { check "waits" "$(tr '\n' ' ' <"$case_dir/slept" | sed 's/ $//')" "$1"; }
expect_calls() { check "api calls" "$(tr '\n' ' ' <"$case_dir/calls" | sed 's/ $//')" "$1"; }
expect_output() {
  if ! grep -qF -- "$1" "$case_dir/out"; then
    echo "FAIL [$case_name] output lacks: $1" >&2
    failures=$((failures + 1))
  fi
}
finish_case() {
  if [ "$failures" -ne "${failures_before:-0}" ]; then
    echo "---- output of [$case_name] ----" >&2
    cat "$case_dir/out" >&2
  fi
  failures_before=$failures
}

one_pr="repos/rolter-ai/rolter/pulls/2035"
open_prs="repos/rolter-ai/rolter/pulls?state=open&per_page=100"

# ── pull_request: the live body ───────────────────────────────────────────────
# #2035: the url lands while the gate runs. the payload still has the clean
# body, and the step has to read past it
start_case "a url added after the event fired is caught"
set_live_body "$dirty"
run_step pull_request
expect_rc 1
expect_output "agent session or remote-connection url found in pr body for #2035"
expect_calls "$one_pr"
expect_slept ""
finish_case

# the #1565 order: the footer was in the body when the pr opened and was
# stripped before this step ran, so the run that opened the pr goes green
start_case "a url stripped before the step ran passes"
payload_body=$dirty
run_step pull_request
expect_rc 0
expect_calls "$one_pr"
finish_case

start_case "another agent's session trailer is caught"
set_live_body "$trailer"
run_step pull_request
expect_rc 1
expect_output "agent session or remote-connection url found in pr body for #2035"
finish_case

start_case "a pr with no body passes"
set_live_body null
run_step pull_request
expect_rc 0
finish_case

start_case "a flaking api is retried and the dirty body still found"
set_live_body "$dirty"
echo 2 >"$case_dir/faults"
run_step pull_request
expect_rc 1
expect_slept "5 5"
expect_calls "$one_pr $one_pr $one_pr"
expect_output "agent session or remote-connection url found in pr body for #2035"
finish_case

start_case "a flaking api is retried to a clean pass"
echo 2 >"$case_dir/faults"
run_step pull_request
expect_rc 0
expect_slept "5 5"
finish_case

start_case "an api that stays down fails closed"
echo 3 >"$case_dir/faults"
run_step pull_request
expect_rc 1
expect_slept "5 5"
expect_calls "$one_pr $one_pr $one_pr"
expect_output "could not read pull request #2035 in rolter-ai/rolter after 3 attempts"
finish_case

start_case "an answer about another pr fails closed"
echo '{"number": 1, "body": ""}' >"$case_dir/respond"
run_step pull_request
expect_rc 1
expect_output "is not that pull request"
finish_case

start_case "an answer that is not json fails closed"
echo '<html>unicorn</html>' >"$case_dir/respond"
run_step pull_request
expect_rc 1
expect_output "is not that pull request"
finish_case

start_case "a payload with no pr number fails before any call"
run_step pull_request ""
expect_rc 1
expect_output "is not a pull request number"
expect_calls ""
finish_case

# ── workflow_dispatch: the pr resolved by head ref ────────────────────────────
start_case "dispatch checks the open pr for the ref"
set_live_body "$dirty"
run_step workflow_dispatch "" fix/2035-live-body
expect_rc 1
expect_output "agent session or remote-connection url found in pr body for fix/2035-live-body"
expect_calls "$open_prs"
finish_case

start_case "dispatch on a ref with no open pr passes with a notice"
run_step workflow_dispatch "" some/other-branch
expect_rc 0
expect_output "no open pull request has some/other-branch as its head"
finish_case

start_case "dispatch retries a flaking listing"
echo 1 >"$case_dir/faults"
run_step workflow_dispatch "" fix/2035-live-body
expect_rc 0
expect_slept "5"
finish_case

start_case "dispatch fails closed when the listing stays down"
echo 3 >"$case_dir/faults"
run_step workflow_dispatch "" fix/2035-live-body
expect_rc 1
expect_output "could not read the open pull requests for rolter-ai/rolter after 3 attempts"
finish_case

# ── merge_group: the pr resolved from the queue ref ───────────────────────────
start_case "a queue run checks the queued pr"
set_live_body "$dirty"
run_step merge_group "" "$queue_ref"
expect_rc 1
expect_output "agent session or remote-connection url found in pr body for #2035 (merge queue)"
finish_case

start_case "a queue run whose pr is not open fails closed"
run_step merge_group "" "gh-readonly-queue/master/pr-9999-0123456789abcdef0123456789abcdef01234567"
expect_rc 1
expect_output "pull request #9999 from gh-readonly-queue/master/pr-9999-"
finish_case

if [ "$failures" -ne 0 ]; then
  echo "$failures check(s) failed" >&2
  exit 1
fi
echo "agent-session-urls: every case passed"
